Retrieve decklists from NetrunnerDB
Project-NISEI/cobra pull request #124
Opened 2023-03-25 16:24 UTC by haradan

Initial UI for choosing a deck to register loaded from the NetrunnerDB API.

Other issues exist to store the registration, display it to the TO, etc.

2023-04-08 17:10 UTC, plural requested changes
this is a great start!

2023-04-08 17:10 UTC, plural commented on app/views/tournaments/edit.html.slim
I generally like to pull extra things like formatting changes only out into their own PRs - they aren't related to the functional change.

2023-04-08 17:10 UTC, plural commented on config/spring.rb
a few of your files are missing newlines at the end.  Would you please check your editor settings?

2023-05-05 21:45 UTC, haradan commented on app/views/tournaments/edit.html.slim
I've split this out to PR #128.

2023-05-05 21:49 UTC, haradan commented on config/spring.rb
This file was generated automatically by my IDE when I ran in debug mode. It looks like it only cares about newlines around functions and classes. I've added them manually.

It looks like the other places in this PR are where there wasn't a newline before and there is one now.

2023-05-06 16:16 UTC, plural commented
This looks pretty great.  How do you want to feature flag this?

2023-05-06 21:14 UTC, haradan commented on app/views/tournaments/_deck_selection.html.slim
> +          - unless deck[:identity].nil?
I'm not really happy with the pinning behaviour yet. It covers up some of the list so if you select one further down you can't select the top one without selecting another one on the first page first.

2023-05-06 23:20 UTC, haradan commented
> This looks pretty great. How do you want to feature flag this?

I've just added Flipper: https://github.com/jnunemaker/flipper

2023-05-06 23:21 UTC, haradan commented on app/views/tournaments/_deck_selection.html.slim
> +          - unless deck[:identity].nil?
I've made it just always show the selected decks, but I've made it a smaller display.

2023-05-16 22:55 UTC, haradan commented
Closing, reopened from a fork: https://github.com/Project-NISEI/cobra/pull/132

2023-05-16 22:55 UTC, closed without merging