Test client side rendering endpoint for pairings
Project-NISEI/cobra pull request #265
Opened 2024-02-23 18:36 UTC by haradan

2024-03-09 17:11 UTC, plural requested changes
Are you able to hide the random seed changes more?  Perhaps a helper that these use without passing it around as much and that you can replace for the tests?

2024-03-09 20:24 UTC, haradan commented on spec/requests/rounds_controller_spec.rb
> +end
You mean newlines at the end of the file? Will do.

2024-03-09 20:24 UTC, haradan commented on app/controllers/rounds_controller.rb
> -      tournament_id: @tournament.id,
Yes, it's not used.

2024-03-09 22:59 UTC, haradan commented
> Are you able to hide the random seed changes more? Perhaps a helper that these use without passing it around as much and that you can replace for the tests?

I don't know what you'd use for this in Rails, and I'm not sure I'd want to hide it. It took some digging to find out where the randomness was coming from. It sounds like helpers are intended to be used in views, and are occasionally made available in controllers?

The level of indirection makes it awkward to pass it around everywhere, but maybe the indirection is the problem. It might be better to instantiate the pairer directly rather than calling pair on the round or stage?

2024-03-17 06:09 UTC, plural commented
> > Are you able to hide the random seed changes more? Perhaps a helper that these use without passing it around as much and that you can replace for the tests?
> 
> I don't know what you'd use for this in Rails, and I'm not sure I'd want to hide it. It took some digging to find out where the randomness was coming from. It sounds like helpers are intended to be used in views, and are occasionally made available in controllers?
> 
> The level of indirection makes it awkward to pass it around everywhere, but maybe the indirection is the problem. It might be better to instantiate the pairer directly rather than calling pair on the round or stage?

i think that is worth a shot, yeah.  I think you can leave it for a separate PR, though, if you want.

2024-03-29 22:58 UTC, merged