Fix assets precompile
Project-NISEI/cobra pull request #275
Opened 2024-03-31 13:54 UTC by haradan

2024-03-31 15:05 UTC, plural requested changes

2024-03-31 15:05 UTC, plural commented on config/secrets.build.yml
this should not be checked in.  If you need this during build it can be handled with a secret in the repo that invokes the docker commands to build.

does the assets precompilation step require access to a secret or are you doing too much in this PR?

2024-03-31 15:23 UTC, haradan commented on config/secrets.build.yml
I think it just validates the environment configuration when you run a rake task, and it won't run without a secret key base in the production environment. I just copied it from secrets.example.yml, which is already checked in, just for testing.

2024-08-16 05:04 UTC, plural commented
does this need to be tidied up before getting submitted?  Is it still needed at all?

2024-08-17 21:40 UTC, haradan commented
Yes, it needs bringing up to date and testing. I'm not sure if there's a better way to do it, but it takes away an extra step during deployment if we can compile the assets in the Docker build.

2024-09-01 16:22 UTC, plural requested changes

2024-09-01 16:22 UTC, plural commented on Dockerfile
> +ENV SECRET_KEY_BASE=55ca41d1c22ee9842aeef2aa5641c063f369e142723586958bd3b36921ca7026bdbf8b98a78376510bd351f790ed99c308e8cf5633b6e4ac678a0e8ef998f6dc
why is this specified?

Can you make this come from the env but not specify a value for it here?  We can use a secret in github for builds there and local env var population elsewhere.

2024-09-01 23:41 UTC, merged